import React from "react";

const sizeClasses = {
  txtLatoSemiBold24: "font-lato font-semibold",
  txtOpenSansRomanBold16Black900d1: "font-bold font-opensans",
  txtInterRegular20: "font-inter font-normal",
  txtOpenSansRomanSemiBold20Black90089: "font-opensans font-semibold",
  txtInterBold60: "font-bold font-inter",
  txtIstokWebRegular40: "font-istokweb font-normal",
  txtSourceSansProSemiBold1744Black90051: "font-semibold font-sourcesanspro",
  txtOpenSansRomanSemiBold24Black900e2: "font-opensans font-semibold",
  txtInterRegular10: "font-inter font-normal",
  txtLatoBold20: "font-bold font-lato",
  txtOpenSansRomanSemiBold32: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold30: "font-opensans font-semibold",
  txtOpenSansRegular16: "font-normal font-opensans",
  txtPoppinsRegular15: "font-normal font-poppins",
  txtPoppinsBold25WhiteA700: "font-bold font-poppins",
  txtOpenSansRomanRegular12: "font-normal font-opensans",
  txtInterBold50: "font-bold font-inter",
  txtPoppinsSemiBold24: "font-poppins font-semibold",
  txtOpenSansRegular10: "font-normal font-opensans",
  txtInterSemiBold40: "font-inter font-semibold",
  txtPoppinsSemiBold20: "font-poppins font-semibold",
  txtInterBold60Black900: "font-bold font-inter",
  txtPoppinsRegular20: "font-normal font-poppins",
  txtInterRegular15: "font-inter font-normal",
  txtOpenSansRomanSemiBold24Gray700: "font-opensans font-semibold",
  txtOpenSansRomanBold45: "font-bold font-opensans",
  txtInterBold20Black900: "font-bold font-inter",
  txtOpenSansRomanSemiBold24RedA400: "font-opensans font-semibold",
  txtPoppinsBold20Amber600: "font-bold font-poppins",
  txtOpenSansRomanSemiBold20: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold16Black900d1: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold24: "font-opensans font-semibold",
  txtOpenSansRegular24: "font-normal font-opensans",
  txtInterBold46: "font-bold font-inter",
  txtInterSemiBold50: "font-inter font-semibold",
  txtInterBold40: "font-bold font-inter",
  txtPoppinsSemiBold36: "font-poppins font-semibold",
  txtOpenSansRegular20: "font-normal font-opensans",
  txtOpenSansRomanRegular25: "font-normal font-opensans",
  txtInterSemiBold55: "font-inter font-semibold",
  txtInterLight10: "font-inter font-light",
  txtOpenSansRomanRegular20: "font-normal font-opensans",
  txtOpenSansRomanSemiBold30WhiteA700: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold24WhiteA700: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold16WhiteA700: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold16: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold16Black900e2: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold14: "font-opensans font-semibold",
  txtInterBold35: "font-bold font-inter",
  txtOpenSansSemiBold1308: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold20Black900d3: "font-opensans font-semibold",
  txtPoppinsSemiBold48: "font-poppins font-semibold",
  txtInterBold30: "font-bold font-inter",
  txtInterSemiBold60: "font-inter font-semibold",
  txtOpenSansRomanRegular35: "font-normal font-opensans",
  txtInterExtraBold60: "font-extrabold font-inter",
  txtOpenSansRomanBold2388: "font-bold font-opensans",
  txtOpenSansRegular20Black900: "font-normal font-opensans",
  txtLexendDecaRegular40: "font-lexenddeca font-normal",
  txtOpenSansRomanBold16Black900: "font-bold font-opensans",
  txtInterMedium25: "font-inter font-medium",
  txtInterBold60Gray90001: "font-bold font-inter",
  txtPoppinsMedium35: "font-medium font-poppins",
  txtOpenSansRomanBold16: "font-bold font-opensans",
  txtOpenSansRomanSemiBold20Black900e2: "font-opensans font-semibold",
  txtInterBold20: "font-bold font-inter",
  txtSourceSansProSemiBold1744: "font-semibold font-sourcesanspro",
  txtOpenSansRomanBold14: "font-bold font-opensans",
  txtInterMedium30: "font-inter font-medium",
  txtOpenSansRomanBold18: "font-bold font-opensans",
  txtPoppinsMedium30: "font-medium font-poppins",
  txtPoppinsSemiBold20Bluegray800: "font-poppins font-semibold",
  txtOpenSansRomanBold12: "font-bold font-opensans",
  txtPoppinsRegular64Indigo900: "font-normal font-poppins",
  txtPoppinsBold48: "font-bold font-poppins",
  txtPoppinsBold40: "font-bold font-poppins",
  txtInterBold16: "font-bold font-inter",
  txtInterMedium16: "font-inter font-medium",
  txtOpenSansRomanRegular20Black90089: "font-normal font-opensans",
  txtInterMedium20: "font-inter font-medium",
  txtPoppinsRegular64: "font-normal font-poppins",
  txtOpenSansRomanRegular35Black900: "font-normal font-opensans",
  txtOpenSansRomanSemiBold24Black900d1: "font-opensans font-semibold",
  txtPoppinsBold18: "font-bold font-poppins",
  txtOpenSansRomanSemiBold24Black900d3: "font-opensans font-semibold",
  txtInterRegular40: "font-inter font-normal",
  txtInterBold80Black900: "font-bold font-inter",
  txtOpenSansRomanSemiBold16RedA700: "font-opensans font-semibold",
  txtPoppinsRegular64Indigo900e0: "font-normal font-poppins",
  txtInterExtraLight15: "font-inter font-thin",
  txtOpenSansRomanExtraBold24: "font-extrabold font-opensans",
  txtOpenSansRomanSemiBold24Black900cc: "font-opensans font-semibold",
  txtInterBold80: "font-bold font-inter",
  txtOpenSansRomanSemiBold32Black900d1: "font-opensans font-semibold",
  txtLexendDecaLight40: "font-lexenddeca font-light",
  txtOpenSansRomanRegular20Black900d1: "font-normal font-opensans",
  txtLexendDecaRegular50: "font-lexenddeca font-normal",
  txtInterRegular30: "font-inter font-normal",
  txtPoppinsBold20: "font-bold font-poppins",
  txtPoppinsBold25: "font-bold font-poppins",
  txtLexendDecaLight30: "font-lexenddeca font-light",
  txtInterBold70: "font-bold font-inter",
  txtInterSemiBold20: "font-inter font-semibold",
  txtInterBold71: "font-bold font-inter",
  txtOpenSansRomanSemiBold16Gray700: "font-opensans font-semibold",
  txtOpenSansRomanExtraBold16: "font-extrabold font-opensans",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
